package com.hanz.youmetalk;

import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;

@GlideModule
public class MyAppGlideModule extends AppGlideModule {
    // since we only going to use the Enhanced API generated by Glide App
    // We can just leave this class empty
    // if in future we want to customise the Glide behaviour we can config inside this class
}
